parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'airbnb'
  - 'prettier'
  - 'prettier/react'
rules:
  linebreak-style:
    - error
    - unix
settings:
  'import/resolver':
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
